# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 6, 12, 13, 10, 17, 467713, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
